In [1]:
# Importing the required libraries for extracting and storing data
import tweepy 
import json

In [2]:
# API credentials required for using twitter data
consumer_key = '********'
consumer_secret = '*****'
access_key = '******'
access_secret = '*******'

In [8]:

username = "@midasIIITD"         
# Authorization to consumer key and consumer secret 
auth = tweepy.OAuthHandler(consumer_key, consumer_secret) 
  
# Access to user's access key and access secret 
auth.set_access_token(access_key, access_secret) 
  
# Calling api 
# used proxy due to college lan issue 
api = tweepy.API(auth,proxy='https://ibm:place!7ibm20@172.27.16.15:3128' ,wait_on_rate_limit=True, wait_on_rate_limit_notify=True, compression=True)
tweets = api.user_timeline(screen_name=username) 
        
# Creating an Empty List so that multiple Jsonline strings can be appended to a same file 
l=[]
# Extracting the json file of each tweet and appending it to the list
for tweet in tweets:
    l.append(tweet._json)
            
# saving the tweet data into a jsonline file having extension jsonl 
list_json=json.dumps(l, indent=4)
with open('tweet_data.jsonl','w') as outfile:
    outfile.write(list_json)

In [10]:
import pandas as pd 
list_final = []        
with open('tweet_data.jsonl') as json_file:  
    data = json.load(json_file)
    for datax in data:
        list2 = [datax['text'],datax['created_at'],datax['favorite_count'],datax['retweet_count']]
        list_final.append(list2)
df = pd.DataFrame(list_final, columns = ['text', 'time','likes','retweets'])
df

,text,time,likes,retweets
0,RT @IIITDelhi: We are delighted to share that ...,Tue Apr 09 16:45:07 +0000 2019,0,9
1,RT @Harvard: Professor Jelani Nelson founded A...,Tue Apr 09 05:04:27 +0000 2019,0,35
2,RT @emnlp2019: For anyone interested in submit...,Tue Apr 09 05:04:11 +0000 2019,0,13
3,RT @multimediaeval: Announcing the 2019 MediaE...,Mon Apr 08 19:38:09 +0000 2019,0,15
4,"Many Congratulations to @midasIIITD student, S...",Mon Apr 08 07:08:12 +0000 2019,16,2
5,@midasIIITD thanks all students who have appea...,Mon Apr 08 03:27:42 +0000 2019,5,0
6,"@himanchalchandr Meanwhile, complete CV/NLP ta...",Sun Apr 07 14:17:29 +0000 2019,0,0
7,@sayangdipto123 Submit as per the guideline ag...,Sun Apr 07 14:17:09 +0000 2019,0,0
8,We request all students whose interview are sc...,Sun Apr 07 11:43:24 +0000 2019,1,1
9,"Other queries: ""none of the Tweeter Apis give ...",Sun Apr 07 06:55:19 +0000 2019,5,2
10,"Other queries: ""do we have to make two differe...",Sun Apr 07 06:53:38 +0000 2019,4,1
11,"Other queries: ""If using Twitter api, it does ...",Sun Apr 07 05:32:27 +0000 2019,6,1
12,Response to some queries asked by students on ...,Sun Apr 07 05:29:40 +0000 2019,7,1
13,RT @kdnuggets: Top 8 #Free Must-Read #Books on...,Sat Apr 06 17:11:29 +0000 2019,0,2
14,@nupur_baghel @PennDATS Congratulation @nupur_...,Sat Apr 06 16:43:27 +0000 2019,18,3
15,We have emailed the task details to all candid...,Fri Apr 05 16:08:37 +0000 2019,11,1
16,RT @rfpvjr: Our NAACL paper on polarization in...,Fri Apr 05 04:05:11 +0000 2019,0,16
17,RT @kdnuggets: Effective Transfer Learning For...,Fri Apr 05 04:04:43 +0000 2019,0,11
18,RT @stanfordnlp: What’s new in @Stanford CS224...,Wed Apr 03 18:31:53 +0000 2019,0,59
19,RT @DeepMindAI: Today we're releasing a large-...,Wed Apr 03 17:04:32 +0000 2019,0,871